const SYSTEMS = [
  {
    id: "integumen",
    name: "Sistem Integumen",
    shortName: "Kulit",
    emoji: "🛡️",
    color: "#0d9488",
    analogi: "Jaket pintar yang melindungi, merasakan, dan mengatur suhu.",
    ringkasan:
      "Lapisan pelindung tubuh: kulit, rambut, kuku, dan kelenjar keringat.",
    fungsi: [
      "Melindungi tubuh dari benturan ringan, kuman, dan sinar matahari berlebih",
      "Membantu mengatur suhu lewat keringat dan aliran darah di kulit",
      "Menjadi indra peraba (panas, dingin, tekan, nyeri)",
      "Membantu pembentukan vitamin D saat terkena sinar matahari dengan bijak",
    ],
    organ: [
      { nama: "Kulit", peran: "Perisai utama, tempat saraf peraba" },
      { nama: "Rambut", peran: "Melindungi kulit kepala dan membantu suhu" },
      { nama: "Kuku", peran: "Melindungi ujung jari" },
      { nama: "Kelenjar keringat", peran: "Mengeluarkan keringat untuk mendinginkan tubuh" },
    ],
    fakta: [
      "Kulit adalah organ terbesar di tubuh manusia.",
      "Keringat hampir tidak berbau; bau biasanya dari bakteri di permukaan kulit.",
      "Mencuci tangan dengan sabun merusak lapisan minyak kuman, bukan hanya 'mencuci kotoran'.",
    ],
    jaga: [
      "Mandi dan jaga kebersihan kulit serta kuku",
      "Pakai tabir surya atau cari teduh saat panas terik",
      "Jangan memencet luka atau jerawat dengan tangan kotor",
    ],
  },
  {
    id: "rangka",
    name: "Sistem Rangka",
    shortName: "Tulang",
    emoji: "🦴",
    color: "#78716c",
    analogi: "Rangka tenda: menegakkan bentuk dan melindungi isi di dalamnya.",
    ringkasan:
      "Tulang, sendi, dan tulang rawan yang menopang tubuh serta melindungi organ.",
    fungsi: [
      "Memberi bentuk dan postur tubuh",
      "Melindungi organ (tengkorak melindungi otak, rusuk melindungi jantung dan paru)",
      "Tempat otot menempel supaya kita bisa bergerak",
      "Menyimpan mineral dan membuat sel darah di sumsum tulang",
    ],
    organ: [
      { nama: "Tulang", peran: "Penopang keras dan penyimpan mineral" },
      { nama: "Sendi", peran: "Penghubung tulang agar bisa ditekuk" },
      { nama: "Tulang rawan", peran: "Bantalan lentur di ujung tulang dan telinga/hidung" },
      { nama: "Sumsum tulang", peran: "Pabrik sel darah" },
    ],
    fakta: [
      "Bayi punya lebih banyak tulang daripada orang dewasa karena beberapa tulang kemudian menyatu.",
      "Tulang hidup: terus diperbaiki, bukan benda mati seperti batu.",
      "Kalsium dan vitamin D penting agar tulang tetap kuat.",
    ],
    jaga: [
      "Gerak aktif setiap hari, misalnya jalan atau olahraga sekolah",
      "Cukupi susu/sumber kalsium dan tidur cukup",
      "Pakai alat pelindung saat bersepeda atau olahraga benturan",
    ],
  },
  {
    id: "otot",
    name: "Sistem Otot",
    shortName: "Otot",
    emoji: "💪",
    color: "#dc2626",
    analogi: "Mesin penggerak yang menarik tali (tulang) supaya badan bergerak.",
    ringkasan:
      "Otot rangka, otot polos, dan otot jantung yang menghasilkan gerakan dan panas.",
    fungsi: [
      "Menggerakkan tubuh bersama tulang dan sendi",
      "Menjaga postur agar tidak ambruk",
      "Membantu organ dalam bekerja (usus mendorong makanan, jantung memompa darah)",
      "Menghasilkan panas saat menggigil atau berolahraga",
    ],
    organ: [
      { nama: "Otot rangka", peran: "Otot yang kita kendalikan, menempel di tulang" },
      { nama: "Otot polos", peran: "Bekerja otomatis di organ dalam" },
      { nama: "Otot jantung", peran: "Otot khusus yang tidak lelah memompa darah" },
      { nama: "Tendon", peran: "Tali kuat yang mengikat otot ke tulang" },
    ],
    fakta: [
      "Jantung adalah otot yang bekerja tanpa istirahat seumur hidup.",
      "Otot membesar karena dilatih, bukan karena 'obat ajaib'.",
      "Pemanasan mengurangi risiko kram dan cedera saat olahraga.",
    ],
    jaga: [
      "Latihan kekuatan dan peregangan secara seimbang",
      "Minum air sebelum, selama, dan sesudah aktivitas",
      "Istirahatkan otot yang nyeri, jangan dipaksa",
    ],
  },
  {
    id: "saraf",
    name: "Sistem Saraf",
    shortName: "Saraf",
    emoji: "🧠",
    color: "#7c3aed",
    analogi: "Pusat komando plus jaringan kabel listrik ke seluruh badan.",
    ringkasan:
      "Otak, sumsum tulang belakang, dan saraf yang mengendalikan pikiran, gerak, dan indra.",
    fungsi: [
      "Menerima informasi dari mata, telinga, kulit, dan indra lain",
      "Mengolah informasi: berpikir, mengingat, merasakan emosi",
      "Mengirim perintah ke otot",
      "Mengatur banyak kerja otomatis seperti detak jantung dan napas",
    ],
    organ: [
      { nama: "Otak", peran: "Pusat kendali utama" },
      { nama: "Sumsum tulang belakang", peran: "Jalur pesan antara otak dan tubuh" },
      { nama: "Saraf tepi", peran: "Kabel ke otot, kulit, dan organ" },
      { nama: "Indra", peran: "Penerima sinyal dari dunia luar" },
    ],
    fakta: [
      "Otak memakai energi yang cukup besar meski hanya sebagian kecil berat tubuh.",
      "Tidur bukan 'waktu terbuang': otak merapikan memori saat tidur.",
      "Refleks lutut terjadi lewat sumsum tulang belakang, lebih cepat daripada pikir dulu.",
    ],
    jaga: [
      "Tidur cukup sesuai usia",
      "Pakai helm, jangan main HP saat menyeberang",
      "Batasi layar malam agar tidur lebih nyenyak",
    ],
  },
  {
    id: "endokrin",
    name: "Sistem Endokrin",
    shortName: "Hormon",
    emoji: "⚗️",
    color: "#d97706",
    analogi: "Sistem pesan kimia: kelenjar mengirim 'surat' (hormon) lewat darah.",
    ringkasan:
      "Kelenjar yang melepaskan hormon untuk mengatur tumbuh kembang, energi, dan keseimbangan tubuh.",
    fungsi: [
      "Mengatur pertumbuhan dan perkembangan",
      "Menjaga kadar gula dan energi",
      "Membantu tubuh merespons stres (siaga saat perlu)",
      "Menyelaraskan banyak organ agar bekerja sebagai satu tim",
    ],
    organ: [
      { nama: "Hipofisis", peran: "Kelenjar 'komandan' di bawah otak" },
      { nama: "Tiroid", peran: "Mengatur kecepatan metabolisme" },
      { nama: "Pankreas", peran: "Menghasilkan insulin untuk kadar gula darah" },
      { nama: "Anak ginjal (adrenal)", peran: "Hormon siaga dan keseimbangan garam" },
    ],
    fakta: [
      "Hormon bekerja lebih lambat daripada saraf, tapi efeknya bisa lebih lama.",
      "Pankreas termasuk organ 'ganda': membantu pencernaan dan menghasilkan hormon.",
      "Perubahan tubuh saat remaja sebagian besar diatur sistem ini.",
    ],
    jaga: [
      "Makan teratur, jangan bolong-bolong ekstrem",
      "Tidur dan kelola stres dengan olahraga atau hobi",
      "Kalau tumbuh kembang terasa sangat berbeda dari teman sebaya, konsultasikan ke orang tua dan dokter",
    ],
  },
  {
    id: "kardiovaskular",
    name: "Sistem Kardiovaskular",
    shortName: "Jantung",
    emoji: "❤️",
    color: "#e11d48",
    analogi: "Pompa dan jaringan jalan raya untuk mengantar 'paket' ke seluruh kota.",
    ringkasan:
      "Jantung, pembuluh darah, dan darah yang mengedarkan oksigen serta nutrisi.",
    fungsi: [
      "Memompa darah ke seluruh tubuh",
      "Mengantar oksigen dan sari makanan",
      "Mengangkut sisa zat untuk dibuang",
      "Membantu menjaga suhu dan menyebar sel pertahanan",
    ],
    organ: [
      { nama: "Jantung", peran: "Pompa berotot di dada kiri" },
      { nama: "Arteri", peran: "Pembuluh yang membawa darah keluar dari jantung" },
      { nama: "Vena", peran: "Pembuluh yang mengembalikan darah ke jantung" },
      { nama: "Kapiler", peran: "Pembuluh sangat halus tempat tukar zat" },
    ],
    fakta: [
      "Jantung orang istirahat biasanya berdetak puluhan kali per menit; bertambah saat lari.",
      "Darah lengkap berisi plasma, sel darah merah, sel darah putih, dan keping darah.",
      "Olahraga teratur membuat jantung lebih efisien, bukan 'aus'.",
    ],
    jaga: [
      "Gerak setiap hari, kurangi duduk terlalu lama",
      "Pilih camilan lebih sering buah/kacang daripada makanan sangat asin atau manis",
      "Jangan merokok dan hindari asap rokok",
    ],
  },
  {
    id: "limfatik",
    name: "Sistem Limfatik & Imun",
    shortName: "Imun",
    emoji: "🛡️",
    color: "#059669",
    analogi: "Petugas kebersihan plus tentara penjaga yang berkeliling di belakang layar.",
    ringkasan:
      "Getah bening, kelenjar getah bening, limpa, dan sel darah putih yang menjaga tubuh.",
    fungsi: [
      "Mengalirkan cairan berlebih kembali ke darah",
      "Menyaring kuman di kelenjar getah bening",
      "Menghasilkan dan menyimpan sel pertahanan",
      "Membantu tubuh mengingat kuman yang pernah dikalahkan (dasar vaksin)",
    ],
    organ: [
      { nama: "Kelenjar getah bening", peran: "Pos pemeriksaan kuman" },
      { nama: "Limpa", peran: "Menyaring darah dan membantu imun" },
      { nama: "Timus", peran: "Tempat 'sekolah' sebagian sel imun saat tumbuh" },
      { nama: "Sel darah putih", peran: "Pasukan yang menyerang kuman" },
    ],
    fakta: [
      "Bengkak di leher saat pilek sering berarti kelenjar sedang bekerja, bukan selalu 'penyakit aneh'.",
      "Vaksin melatih imun tanpa harus sakit parah dulu.",
      "Tidur kurang membuat pertahanan tubuh lebih lemah.",
    ],
    jaga: [
      "Cuci tangan, vaksin sesuai jadwal sekolah/posyandu",
      "Tidur cukup dan makan beragam",
      "Jangan minum antibiotik sembarangan tanpa resep dokter",
    ],
  },
  {
    id: "pernapasan",
    name: "Sistem Pernapasan",
    shortName: "Paru",
    emoji: "🌬️",
    color: "#0284c7",
    analogi: "Pabrik tukar gas: masuk oksigen, keluar karbon dioksida.",
    ringkasan:
      "Hidung, saluran napas, dan paru-paru untuk pertukaran oksigen dan karbon dioksida.",
    fungsi: [
      "Mengambil oksigen dari udara",
      "Membuang karbon dioksida",
      "Membantu berbicara (udara melewati pita suara)",
      "Menyaring debu dan kuman di hidung serta saluran napas",
    ],
    organ: [
      { nama: "Hidung", peran: "Menyaring, menghangatkan, dan melembapkan udara" },
      { nama: "Tenggorokan & trakea", peran: "Pipa udara ke paru" },
      { nama: "Bronkus", peran: "Percabangan saluran di dalam paru" },
      { nama: "Alveolus", peran: "Kantung halus tempat oksigen masuk ke darah" },
    ],
    fakta: [
      "Kita bernapas otomatis, tapi bisa juga menahan atau mengatur napas sejenak.",
      "Olahraga membuat tubuh lebih efisien memakai oksigen.",
      "Asap rokok merusak silia, 'sapu' kecil di saluran napas.",
    ],
    jaga: [
      "Jauhi asap rokok dan polusi sedapat mungkin",
      "Bernapas lewat hidung saat udara berdebu",
      "Pakai masker jika sedang flu agar tidak menulari teman",
    ],
  },
  {
    id: "pencernaan",
    name: "Sistem Pencernaan",
    shortName: "Cerna",
    emoji: "🍎",
    color: "#ea580c",
    analogi: "Pabrik daur ulang makanan menjadi bahan bakar dan bahan bangunan sel.",
    ringkasan:
      "Saluran dari mulut sampai usus besar, plus hati dan pankreas, untuk menguraikan makanan.",
    fungsi: [
      "Memecah makanan menjadi sari yang bisa diserap",
      "Menyerap air dan zat gizi",
      "Membuang sisa yang tidak terpakai",
      "Hati membantu mengolah zat dan menghasilkan empedu",
    ],
    organ: [
      { nama: "Mulut & kerongkongan", peran: "Mengunyah dan mendorong makanan" },
      { nama: "Lambung", peran: "Mengaduk makanan dengan getah lambung" },
      { nama: "Usus halus", peran: "Penyerapan zat gizi utama" },
      { nama: "Hati & pankreas", peran: "Empedu dan enzim pencernaan" },
    ],
    fakta: [
      "Usus halus orang dewasa bisa mencapai beberapa meter, terlipat rapat di perut.",
      "Serat (sayur, buah, gandum utuh) membantu buang air besar teratur.",
      "Mengunyah pelan meringankan kerja lambung.",
    ],
    jaga: [
      "Makan teratur, banyak minum air, cukup sayur dan buah",
      "Cuci tangan sebelum makan",
      "Jangan menelan makanan saat lari atau bergurau (risiko tersedak)",
    ],
  },
  {
    id: "ekskresi",
    name: "Sistem Ekskresi",
    shortName: "Ginjal",
    emoji: "💧",
    color: "#4f46e5",
    analogi: "Filter air plus tempat sampah teratur agar darah tetap bersih.",
    ringkasan:
      "Ginjal dan saluran kemih menyaring limbah dari darah. Kulit dan paru juga membantu membuang sisa zat.",
    fungsi: [
      "Menyaring limbah dan kelebihan garam dari darah",
      "Menjaga keseimbangan air tubuh",
      "Membantu mengatur tekanan darah secara kimiawi",
      "Membuang sisa dalam bentuk urine",
    ],
    organ: [
      { nama: "Ginjal", peran: "Saringan utama kiri dan kanan" },
      { nama: "Ureter", peran: "Pipa dari ginjal ke kandung kemih" },
      { nama: "Kandung kemih", peran: "Kantong penyimpan urine sementara" },
      { nama: "Kulit & paru", peran: "Membuang sedikit sisa lewat keringat dan napas" },
    ],
    fakta: [
      "Warna urine yang sangat gelap sering tanda kurang minum (kecuali obat/makanan tertentu).",
      "Kedua ginjal bekerja cadangan: tubuh bisa hidup dengan satu ginjal yang sehat.",
      "Minuman bersoda atau sangat manis bukan pengganti air putih.",
    ],
    jaga: [
      "Minum air putih yang cukup setiap hari",
      "Jangan menahan buang air terlalu lama kebiasaan",
      "Segera beri tahu orang tua jika nyeri saat buang air atau urine berdarah",
    ],
  },
  {
    id: "reproduksi",
    name: "Sistem Reproduksi",
    shortName: "Tumbuh",
    emoji: "🌱",
    color: "#db2777",
    analogi: "Sistem yang mengatur perubahan menuju dewasa dan kelangsungan generasi.",
    ringkasan:
      "Sistem yang membantu tubuh berubah saat remaja dan berperan dalam kelangsungan generasi manusia. Detail organ dipelajari di kelas IPA/Biologi bersama guru.",
    fungsi: [
      "Membantu perubahan tubuh saat pubertas (tumbuh menuju dewasa)",
      "Menghasilkan hormon yang memengaruhi pertumbuhan",
      "Berperan dalam kelangsungan generasi manusia",
    ],
    organ: [
      { nama: "Kelenjar terkait pertumbuhan", peran: "Membantu mengatur perubahan saat remaja" },
      { nama: "Organ dalam rongga panggul", peran: "Dipelajari secara rinci di sekolah bersama guru" },
    ],
    fakta: [
      "Pubertas terjadi pada usia yang tidak sama pada setiap orang; itu wajar.",
      "Perubahan tubuh remaja diatur bersama sistem endokrin.",
      "Pertanyaan soal perubahan tubuh paling aman ditanyakan ke orang tua, guru IPA, atau dokter.",
    ],
    jaga: [
      "Jaga kebersihan tubuh setiap hari",
      "Hormati tubuh sendiri dan tubuh orang lain",
      "Kalau ada yang terasa sakit atau membingungkan, bicara dengan orang dewasa yang dipercaya",
    ],
  },
];

const QUIZ = [
  {
    q: "Organ terbesar di tubuh manusia adalah…",
    options: ["Jantung", "Kulit", "Hati", "Otak"],
    a: 1,
    explain: "Kulit menutupi hampir seluruh permukaan tubuh, jadi luasnya paling besar.",
  },
  {
    q: "Tulang rusuk terutama melindungi…",
    options: ["Otak", "Ginjal saja", "Jantung dan paru", "Usus besar saja"],
    a: 2,
    explain: "Sangkar rusuk melindungi organ dada: jantung dan paru-paru.",
  },
  {
    q: "Otot yang bekerja memompa darah tanpa kita pikirkan adalah…",
    options: ["Otot betis", "Otot jantung", "Otot biceps", "Otot wajah"],
    a: 1,
    explain: "Otot jantung khusus dan bekerja terus-menerus.",
  },
  {
    q: "Pusat kendali utama sistem saraf adalah…",
    options: ["Hati", "Lambung", "Otak", "Ginjal"],
    a: 2,
    explain: "Otak mengolah informasi dan mengirim perintah.",
  },
  {
    q: "Insulin yang mengatur gula darah dihasilkan terutama oleh…",
    options: ["Paru", "Pankreas", "Kulit", "Telinga"],
    a: 1,
    explain: "Pankreas punya peran hormon sekaligus membantu pencernaan.",
  },
  {
    q: "Pembuluh yang membawa darah keluar dari jantung disebut…",
    options: ["Vena", "Kapiler", "Arteri", "Getah bening"],
    a: 2,
    explain: "Arteri membawa darah menjauh dari jantung.",
  },
  {
    q: "Kelenjar getah bening yang kadang bengkak saat pilek sedang…",
    options: ["Istirahat total", "Menyaring dan melawan kuman", "Membuat tulang", "Mengunyah makanan"],
    a: 1,
    explain: "Itu pos pemeriksaan sistem imun.",
  },
  {
    q: "Pertukaran oksigen dan karbon dioksida terjadi di…",
    options: ["Alveolus paru", "Lambung", "Kuku", "Rambut"],
    a: 0,
    explain: "Alveolus adalah kantung halus di ujung saluran napas.",
  },
  {
    q: "Penyerapan zat gizi makanan terutama terjadi di…",
    options: ["Mulut saja", "Usus halus", "Batang otak", "Kelenjar keringat"],
    a: 1,
    explain: "Dinding usus halus dirancang untuk menyerap sari makanan.",
  },
  {
    q: "Organ utama yang menyaring darah menjadi urine adalah…",
    options: ["Limpa", "Ginjal", "Lidah", "Hidung"],
    a: 1,
    explain: "Ginjal menyaring limbah dan kelebihan zat dari darah.",
  },
  {
    q: "Vitamin D pada kulit terbantu terbentuk jika…",
    options: ["Tidak pernah kena cahaya", "Terkena sinar matahari secara bijak", "Minum soda", "Menahan napas"],
    a: 1,
    explain: "Kulit membantu membentuk vitamin D dengan bantuan sinar matahari.",
  },
  {
    q: "Sel darah banyak dibuat di…",
    options: ["Sumsum tulang", "Rambut", "Kuku", "Kornea mata"],
    a: 0,
    explain: "Sumsum tulang adalah 'pabrik' sel darah.",
  },
];
